(function(){/*
 http://google-maps-utility-library-v3.googlecode.com
*/
var i,k=Math.PI/180,aa=0,l=google.maps,m,o,p,r={ba:null,W:false},s={},t={};function u(a,b,c){var d=b===""?0:a.indexOf(b);return a.substring(d+b.length,c===""?a.length:a.indexOf(c,d+b.length))}function v(a){return a&&typeof a==="string"}function w(a,b,c){if(a&&b){var d;for(d in a)if(c||!(d in b))b[d]=a[d]}return b}function x(){l.event.trigger.apply(this,arguments)}function ba(a,b){var c="";if(a)c+=a.getTime()-a.getTimezoneOffset()*6E4;if(b)c+=", "+(b.getTime()-b.getTimezoneOffset()*6E4);return c}
function y(a,b){b=Math.min(Math.max(b,0),1);if(a){var c=a.style;if(typeof c.opacity!=="undefined")c.opacity=b;if(typeof c.filters!=="undefined")c.filters.alpha.opacity=Math.floor(100*b);if(typeof c.filter!=="undefined")c.filter="alpha(opacity:"+Math.floor(b*100)+")"}}function ca(a){var b="";for(var c in a)if(a.hasOwnProperty(c)){if(b.length>0)b+=";";b+=c+":"+a[c]}return b}
function da(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}throw new Error("This browser does not support XMLHttpRequest.");}else return new XMLHttpRequest}var z="esriGeometryPoint",A="esriGeometryMultipoint",B="esriGeometryPolyline",C="esriGeometryPolygon",D="esriGeometryEnvelope";
function ea(a){var b=a;if(a&&a.splice&&a.length>0)b=a[0];if(b instanceof l.LatLng||b instanceof l.Marker)return a&&a.splice&&a.length>1?A:z;else if(b instanceof l.Polyline)return B;else if(b instanceof l.Polygon)return C;else if(b instanceof l.LatLngBounds)return D;else if(b.x!==undefined&&b.y!==undefined)return z;else if(b.points)return A;else if(b.paths)return B;else if(b.rings)return C;return null}
function E(a){var b=a;if(a&&a.splice&&a.length>0)b=a[0];if(b&&b.splice&&b.length>0)b=b[0];if(b instanceof l.LatLng||b instanceof l.Marker||b instanceof l.Polyline||b instanceof l.Polygon||b instanceof l.LatLngBounds)return true;return false}function F(a,b){for(var c=[],d,e=0,f=a.getLength();e<f;e++){d=a.getAt(e);c.push("["+d.lng()+","+d.lat()+"]")}b&&c.length>0&&c.push("["+a.getAt(0).lng()+","+a.getAt(0).lat()+"]");return c.join(",")}
function G(a){var b;if(typeof a==="object")if(a&&a.splice){b=[];for(var c=0,d=a.length;c<d;c++)b.push(G(a[c]));return"["+b.join(",")+"]"}else if(E(a)){var e;d="{";switch(ea(a)){case z:e=a&&a.splice?a[0]:a;if(e instanceof l.Marker)e=e.getPosition();d+="x:"+e.lng()+",y:"+e.lat();break;case A:c=[];for(b=0;b<a.length;b++){e=a[b]instanceof l.Marker?a[b].getPosition():a[b];c.push("["+e.lng()+","+e.lat()+"]")}d+="points: ["+c.join(",")+"]";break;case B:c=[];a=a&&a.splice?a:[a];for(b=0;b<a.length;b++)c.push("["+
F(a[b].getPath())+"]");d+="paths:["+c.join(",")+"]";break;case C:c=[];e=a&&a.splice?a[0]:a;a=e.getPaths();for(b=0;b<a.getLength();b++)c.push("["+F(a.getAt(b),true)+"]");d+="rings:["+c.join(",")+"]";break;case D:e=a&&a.splice?a[0]:a;d+="xmin:"+e.getSouthWest().lng()+",ymin:"+e.getSouthWest().lat()+",xmax:"+e.getNorthEast().lng()+",ymax:"+e.getNorthEast().lat();break}d+=", spatialReference:{wkid:4326}";d+="}";return d}else if(a.toJSON)return a.toJSON();else{b="";for(c in a)if(a.hasOwnProperty(c)){if(b.length>
0)b+=", ";b+=c+":"+G(a[c])}return"{"+b+"}"}return a.toString()}function H(a){var b="";if(a){a.f=a.f||"json";for(var c in a)if(a.hasOwnProperty(c)&&a[c]!==null&&a[c]!==undefined){var d=G(a[c]);b+=c+"="+(escape?escape(d):encodeURIComponent(d))+"&"}}return b}
function I(a,b,c,d){var e="ags_jsonp_"+aa++ +"_"+Math.floor(Math.random()*1E6),f=null;b=b||{};b[c||"callback"]=e+" && "+e;b=H(b);var j=document.getElementsByTagName("head")[0];if(!j)throw new Error("document must have header tag");window[e]=function(){delete window[e];f&&j.removeChild(f);f=null;d.apply(null,arguments);x(t,"jsonpend",e)};if((b+a).length<2E3&&!r.W){f=document.createElement("script");f.src=a+(a.indexOf("?")===-1?"?":"&")+b;f.id=e;j.appendChild(f)}else{c=window.location;c=c.protocol+
"//"+c.hostname+(!c.port||c.port===80?"":":"+c.port+"/");var h=true;if(a.toLowerCase().indexOf(c.toLowerCase())!==-1)h=false;if(r.W)h=true;if(h&&!r.ba)throw new Error("No proxyUrl property in Config is defined");var g=da();g.onreadystatechange=function(){if(g.readyState===4)if(g.status===200)eval(g.responseText);else throw new Error("Error code "+g.status);};g.open("POST",h?r.ba+"?"+a:a,true);g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");g.send(b)}x(t,"jsonpstart",e);return e}
t.na=function(a,b,c,d){I(a,b,c,d)};t.V=function(a,b){if(b&&b.splice)for(var c,d=0,e=b.length;d<e;d++)if((c=b[d])&&c.splice)t.V(a,c);else E(c)&&c.setMap(a)};t.ra=function(a,b){t.V(null,a);if(b)a.length=0};function J(a){a=a||{};this.wkid=a.wkid;this.wkt=a.wkt}J.prototype.forward=function(a){return a};J.prototype.q=function(a){return a};J.prototype.s=function(){return 360};J.prototype.toJSON=function(){return"{"+(this.wkid?" wkid:"+this.wkid:"wkt: '"+this.wkt+"'")+"}"};
function K(a){a=a||{};J.call(this,a)}K.prototype=new J;function L(a){a=a||{};J.call(this,a);var b=a.N,c=a.S*k,d=a.T*k,e=a.O*k;this.a=a.t/a.unit;this.h=a.r*k;this.k=a.L;this.l=a.M;a=1/b;b=2*a-a*a;this.g=Math.sqrt(b);a=this.m(c,b);b=this.m(d,b);e=M(this,e,this.g);c=M(this,c,this.g);d=M(this,d,this.g);this.b=Math.log(a/b)/Math.log(c/d);this.J=a/(this.b*Math.pow(c,this.b));this.i=this.w(this.a,this.J,e,this.b)}L.prototype=new J;
L.prototype.m=function(a,b){var c=Math.sin(a);return Math.cos(a)/Math.sqrt(1-b*c*c)};function M(a,b,c){a=c*Math.sin(b);return Math.tan(Math.PI/4-b/2)/Math.pow((1-a)/(1+a),c/2)}i=L.prototype;i.w=function(a,b,c,d){return a*b*Math.pow(c,d)};i.v=function(a,b,c){c=b*Math.sin(c);return Math.PI/2-2*Math.atan(a*Math.pow((1-c)/(1+c),b/2))};i.R=function(a,b,c){var d=0;c=c;for(var e=this.v(a,b,c);Math.abs(e-c)>1.0E-9&&d<10;){d++;c=e;e=this.v(a,b,c)}return e};
i.forward=function(a){var b=a[0]*k;a=this.w(this.a,this.J,M(this,a[1]*k,this.g),this.b);b=this.b*(b-this.h);return[this.k+a*Math.sin(b),this.l+this.i-a*Math.cos(b)]};i.q=function(a){var b=a[0]-this.k,c=a[1]-this.l;a=Math.atan(b/(this.i-c));b=Math.pow((this.b>0?1:-1)*Math.sqrt(b*b+(this.i-c)*(this.i-c))/(this.a*this.J),1/this.b);return[(a/this.b+this.h)/k,this.R(b,this.g,Math.PI/2-2*Math.atan(b))/k]};i.s=function(){return Math.PI*2*this.a};
function N(a){a=a||{};J.call(this,a);this.a=a.t/a.unit;var b=a.N;this.C=a.ja;var c=a.O*k;this.h=a.r*k;this.k=a.L;this.l=a.M;a=1/b;this.c=2*a-a*a;this.A=this.c*this.c;this.K=this.A*this.c;this.p=this.c/(1-this.c);this.U=this.m(c,this.a,this.c,this.A,this.K)}N.prototype=new J;N.prototype.m=function(a,b,c,d,e){return b*((1-c/4-3*d/64-5*e/256)*a-(3*c/8+3*d/32+45*e/1024)*Math.sin(2*a)+(15*d/256+45*e/1024)*Math.sin(4*a)-35*e/3072*Math.sin(6*a))};
N.prototype.forward=function(a){var b=a[1]*k,c=a[0]*k;a=this.a/Math.sqrt(1-this.c*Math.pow(Math.sin(b),2));var d=Math.pow(Math.tan(b),2),e=this.p*Math.pow(Math.cos(b),2);c=(c-this.h)*Math.cos(b);var f=this.m(b,this.a,this.c,this.A,this.K);return[this.k+this.C*a*(c+(1-d+e)*Math.pow(c,3)/6+(5-18*d+d*d+72*e-58*this.p)*Math.pow(c,5)/120),this.l+this.C*(f-this.U)+a*Math.tan(b)*(c*c/2+(5-d+9*e+4*e*e)*Math.pow(c,4)/120+(61-58*d+d*d+600*e-330*this.p)*Math.pow(c,6)/720)]};
N.prototype.q=function(a){var b=a[0],c=a[1];a=(1-Math.sqrt(1-this.c))/(1+Math.sqrt(1-this.c));c=(this.U+(c-this.l)/this.C)/(this.a*(1-this.c/4-3*this.A/64-5*this.K/256));a=c+(3*a/2-27*Math.pow(a,3)/32)*Math.sin(2*c)+(21*a*a/16-55*Math.pow(a,4)/32)*Math.sin(4*c)+151*Math.pow(a,3)/6*Math.sin(6*c)+1097*Math.pow(a,4)/512*Math.sin(8*c);c=this.p*Math.pow(Math.cos(a),2);var d=Math.pow(Math.tan(a),2),e=this.a/Math.sqrt(1-this.c*Math.pow(Math.sin(a),2)),f=this.a*(1-this.c)/Math.pow(1-this.c*Math.pow(Math.sin(a),
2),1.5);b=(b-this.k)/(e*this.C);e=a-e*Math.tan(a)/f*(b*b/2-(5+3*d+10*c-4*c*c-9*this.p)*Math.pow(b,4)/24+(61+90*d+28*c+45*d*d-252*this.p-3*c*c)*Math.pow(b,6)/720);return[(this.h+(b-(1+2*d+c)*Math.pow(b,3)/6+(5-2*c+28*d-3*c*c+8*this.p+24*d*d)*Math.pow(b,5)/120)/Math.cos(a))/k,e/k]};N.prototype.s=function(){return Math.PI*2*this.a};function O(a){a=a||{};J.call(this,a);this.a=(a.t||6378137)/(a.unit||1);this.h=(a.r||0)*k}O.prototype=new J;
O.prototype.forward=function(a){var b=a[1]*k;return[this.a*(a[0]*k-this.h),this.a/2*Math.log((1+Math.sin(b))/(1-Math.sin(b)))]};O.prototype.q=function(a){return[(a[0]/this.a+this.h)/k,(Math.PI/2-2*Math.atan(Math.exp(-a[1]/this.a)))/k]};O.prototype.s=function(){return Math.PI*2*this.a};
function P(a){a=a||{};J.call(this,a);var b=a.N,c=a.S*k,d=a.T*k,e=a.O*k;this.a=a.t/a.unit;this.h=a.r*k;this.k=a.L;this.l=a.M;a=1/b;b=2*a-a*a;this.g=Math.sqrt(b);a=this.m(c,b);b=this.m(d,b);c=Q(this,c,this.g);d=Q(this,d,this.g);e=Q(this,e,this.g);this.b=(a*a-b*b)/(d-c);this.I=a*a+this.b*c;this.i=this.w(this.a,this.I,this.b,e)}P.prototype=new J;P.prototype.m=function(a,b){var c=Math.sin(a);return Math.cos(a)/Math.sqrt(1-b*c*c)};
function Q(a,b,c){a=c*Math.sin(b);return(1-c*c)*(Math.sin(b)/(1-a*a)-1/(2*c)*Math.log((1-a)/(1+a)))}i=P.prototype;i.w=function(a,b,c,d){return a*Math.sqrt(b-c*d)/c};i.v=function(a,b,c){var d=b*Math.sin(c);return c+(1-d*d)*(1-d*d)/(2*Math.cos(c))*(a/(1-b*b)-Math.sin(c)/(1-d*d)+Math.log((1-d)/(1+d))/(2*b))};i.R=function(a,b,c){var d=0;c=c;for(var e=this.v(a,b,c);Math.abs(e-c)>1.0E-8&&d<10;){d++;c=e;e=this.v(a,b,c)}return e};
i.forward=function(a){var b=a[0]*k;a=this.w(this.a,this.I,this.b,Q(this,a[1]*k,this.g));b=this.b*(b-this.h);return[this.k+a*Math.sin(b),this.l+this.i-a*Math.cos(b)]};i.q=function(a){var b=a[0]-this.k;a=a[1]-this.l;var c=Math.sqrt(b*b+(this.i-a)*(this.i-a)),d=this.b>0?1:-1;c=(this.I-c*c*this.b*this.b/(this.a*this.a))/this.b;return[(Math.atan(d*b/(d*this.i-d*a))/this.b+this.h)/k,this.R(c,this.g,Math.asin(c/2))/k]};i.s=function(){return Math.PI*2*this.a};i.s=function(){return Math.PI*2*this.a};m=new K({wkid:4326});
o=new K({wkid:4269});p=new O({wkid:102113,t:6378137,r:0,unit:1});s={"4326":m,"4269":o,"102113":p,"102100":new O({wkid:102100,t:6378137,r:0,unit:1})};
t.qa=function(a,b){var c=s[""+a];if(c)return c;if(b instanceof J)c=s[""+a]=b;else{c=b||a;var d={wkt:a};if(a===parseInt(a,10))d={wkid:a};var e=u(c,'PROJECTION["','"]'),f=u(c,"SPHEROID[","]").split(",");if(e!==""){d.unit=parseFloat(u(u(c,"PROJECTION",""),"UNIT[","]").split(",")[1]);d.t=parseFloat(f[1]);d.N=parseFloat(f[2]);d.O=parseFloat(u(c,'"Latitude_Of_Origin",',"]"));d.r=parseFloat(u(c,'"Central_Meridian",',"]"));d.L=parseFloat(u(c,'"False_Easting",',"]"));d.M=parseFloat(u(c,'"False_Northing",',
"]"))}switch(e){case "":c=new J(d);break;case "Lambert_Conformal_Conic":d.S=parseFloat(u(c,'"Standard_Parallel_1",',"]"));d.T=parseFloat(u(c,'"Standard_Parallel_2",',"]"));c=new L(d);break;case "Transverse_Mercator":d.ja=parseFloat(u(c,'"Scale_Factor",',"]"));c=new N(d);break;case "Albers":d.S=parseFloat(u(c,'"Standard_Parallel_1",',"]"));d.T=parseFloat(u(c,'"Standard_Parallel_2",',"]"));c=new P(d);break;default:throw new Error(e+"  not supported");}if(c)s[""+a]=c}return c};
function R(a){this.url=a;this.definition=null}function S(a,b){this.url=a;this.P=false;var c=a.split("/");this.name=c[c.length-2].replace(/_/g," ");b=b||{};b.ka||fa(this)}function fa(a){I(a.url,{},"",function(b){a.B(b)})}S.prototype.B=function(a){var b=this;w(a,this);this.spatialReference=a.spatialReference.wkt?J.pa(a.spatialReference.wkt):s[a.spatialReference.wkid];a.tables!==undefined?I(this.url+"/layers",{},"",function(c){T(b,c)}):T(b,a)};
function T(a,b){var c=[],d=[];a.layers=c;if(b.tables)a.tables=d;var e,f,j,h;f=0;for(j=b.layers.length;f<j;f++){h=b.layers[f];e=new R(a.url+"/"+h.id);w(h,e);e.visible=e.defaultVisibility;c.push(e)}if(b.tables){f=0;for(j=b.tables.length;f<j;f++){h=b.tables[f];e=new R(a.url+"/"+h.id);w(h,e);d.push(e)}}f=0;for(j=c.length;f<j;f++){e=c[f];if(e.subLayerIds){e.G=[];d=0;for(h=e.subLayerIds.length;d<h;d++){var g;a:{g=e.subLayerIds[d];var n=a.layers;if(n)for(var q=0,ga=n.length;q<ga;q++){if(g===n[q].id){g=n[q];
break a}if(v(g)&&n[q].name.toLowerCase()===g.toLowerCase()){g=n[q];break a}}g=null}e.G.push(g);g.oa=e}}}a.P=true;x(a,"load")}function ha(a){var b={};if(a.layers)for(var c=0,d=a.layers.length;c<d;c++){var e=a.layers[c];if(e.definition)b[String(e.id)]=e.definition}return b}
function ia(a){var b=[];if(a.layers){var c,d,e;d=0;for(e=a.layers.length;d<e;d++){c=a.layers[d];if(c.G)for(var f=0,j=c.G.length;f<j;f++)if(c.G[f].visible===false){c.visible=false;break}}d=0;for(e=a.layers.length;d<e;d++){c=a.layers[d];c.visible===true&&b.push(c.id)}}return b}
function U(a,b,c,d){if(b&&b.bounds){var e={};e.f=b.f;var f=b.bounds;e.bbox=""+f.getSouthWest().lng()+","+f.getSouthWest().lat()+","+f.getNorthEast().lng()+","+f.getNorthEast().lat();e.size=""+b.width+","+b.height;e.dpi=b.dpi;if(b.imageSR)e.imageSR=b.imageSR.wkid?b.imageSR.wkid:"{wkt:"+b.imageSR.wkt+"}";e.bboxSR="4326";e.format=b.format;f=b.layerDefinitions;if(f===undefined)f=ha(a);e.layerDefs=ca(f);f=b.layerIds;var j=b.layerOption||"show";if(f===undefined)f=ia(a);if(f.length>0)e.layers=j+":"+f.join(",");
else if(a.P&&c){c({href:null});return}e.transparent=b.transparent===false?false:true;if(b.time)e.time=ba(b.time,b.la);e.ha=b.ha;if(e.f==="image")return a.url+"/export?"+H(e);else I(a.url+"/export",e,"",function(h){if(h.extent){var g,n=h.extent,q=s[n.spatialReference.wkid||n.spatialReference.wkt];q=q||m;g=q.q([n.xmin,n.ymin]);n=q.q([n.xmax,n.ymax]);g=new l.LatLngBounds(new l.LatLng(g[1],g[0]),new l.LatLng(n[1],n[0]));h.bounds=g;delete h.extent;c(h)}else{h=h.error;d&&h&&h.error&&d(h.error)}})}}
function V(a){this.ia=a?a.lods:null;this.u=a?s[a.spatialReference.wkid||a.spatialReference.wkt]:p;if(!this.u)throw new Error("unsupported Spatial Reference");this.ca=a?a.lods[0].resolution:156543.033928;this.minZoom=Math.floor(Math.log(this.u.s()/this.ca/256)/Math.LN2+0.5);this.maxZoom=a?this.minZoom+this.ia.length-1:20;if(l.Size)this.da=a?new l.Size(a.cols,a.rows):new l.Size(256,256);this.F=Math.pow(2,this.minZoom)*this.ca;this.$=a?a.origin.x:-2.0037508342787E7;this.aa=a?a.origin.y:2.0037508342787E7;
if(a)for(var b,c=0;c<a.lods.length-1;c++){b=a.lods[c].resolution/a.lods[c+1].resolution;if(b>2.001||b<1.999)throw new Error("This type of map cache is not supported in V3. \nScale ratio between zoom levels must be 2");}}V.prototype.fromLatLngToPoint=function(a,b){if(!a||isNaN(a.lat())||isNaN(a.lng()))return null;var c=this.u.forward([a.lng(),a.lat()]),d=b||new l.Point(0,0);d.x=(c[0]-this.$)/this.F;d.y=(this.aa-c[1])/this.F;return d};V.prototype.fromLatLngToPoint=V.prototype.fromLatLngToPoint;
V.prototype.fromPointToLatLng=function(a){if(a===null)return null;a=this.u.q([a.x*this.F+this.$,this.aa-a.y*this.F]);return new l.LatLng(a[1],a[0])};var W=new V;
function X(a,b){b=b||{};if(b.opacity){this.e=b.opacity;delete b.opacity}w(b,this);this.d=a instanceof S?a:new S(a);if(b.X){var c=u(this.d.url,"","://");this.ea=c+"://"+b.X+u(this.d.url,c+"://"+u(this.d.url,"://","/"),"");this.Z=parseInt(u(b.X,"[","]"),10)}this.name=b.name||this.d.name;this.maxZoom=b.maxZoom||19;this.minZoom=b.minZoom||0;if(this.d.P)this.B(b);else{var d=this;l.event.addListenerOnce(this.d,"load",function(){d.B(b)})}this.j={};this.Y=b.map}
X.prototype.B=function(a){if(this.d.tileInfo){this.o=new V(this.d.tileInfo);this.minZoom=a.minZoom||this.o.minZoom;this.maxZoom=a.maxZoom||this.o.maxZoom}};
X.prototype.getTileUrl=function(a,b){var c=b-(this.o?this.o.minZoom:this.minZoom),d="";if(!isNaN(a.x)&&!isNaN(a.y)&&c>=0&&a.x>=0&&a.y>=0){d=this.d.url;if(this.ea)d=this.ea.replace("["+this.Z+"]",""+(a.y+a.x)%this.Z);if(this.d.singleFusedMapCache===false){c=this.o||this.Y?this.Y.getProjection():W;if(!c instanceof V)c=W;d=c.da;var e=1<<b,f=new l.Point(a.x*d.width/e,(a.y+1)*d.height/e);e=new l.Point((a.x+1)*d.width/e,a.y*d.height/e);f=new l.LatLngBounds(c.fromPointToLatLng(f),c.fromPointToLatLng(e));
e={f:"image"};e.bounds=f;e.width=d.width;e.height=d.height;e.imageSR=c.u;d=U(this.d,e)}else d=d+"/tile/"+c+"/"+a.y+"/"+a.x}return d};X.prototype.Q=function(a){this.e=a;var b=this.j;for(var c in b)b.hasOwnProperty(c)&&y(b[c],a)};
function Y(a,b){b=b||{};var c;if(b.opacity){this.e=b.opacity;delete b.opacity}w(b,this);var d=a;if(v(a))d=[new X(a,b)];else if(a instanceof S)d=[new X(a,b)];else if(a instanceof X)d=[a];else if(a.length>0&&v(a[0])){d=[];for(c=0;c<a.length;c++)d[c]=new X(a[c],b)}this.H=d;this.j={};if(b.maxZoom!==undefined)this.maxZoom=b.maxZoom;else{var e=0;for(c=0;c<d.length;c++)e=Math.max(e,d[c].maxZoom);this.maxZoom=e}if(d[0].o){this.tileSize=d[0].o.da;this.projection=d[0].o}else this.tileSize=new l.Size(256,256);
if(!this.name)this.name=d[0].name}
Y.prototype.getTile=function(a,b,c){for(var d=c.createElement("div"),e="_"+a.x+"_"+a.y+"_"+b,f=0;f<this.H.length;f++){var j=this.H[f];if(b<=j.maxZoom&&b>=j.minZoom){var h=j.getTileUrl(a,b);if(h){var g=c.createElement(document.all?"img":"div");g.style.border="0px none";g.style.margin="0px";g.style.padding="0px";g.style.overflow="hidden";g.style.position="absolute";g.style.top="0px";g.style.left="0px";g.style.width=""+this.tileSize.width+"px";g.style.height=""+this.tileSize.height+"px";if(document.all)g.src=
h;else g.style.backgroundImage="url("+h+")";d.appendChild(g);j.j[e]=g;if(j.e!==undefined)y(g,j.e);else this.e!==undefined&&y(g,this.e)}}}this.j[e]=d;d.setAttribute("tid",e);return d};Y.prototype.getTile=Y.prototype.getTile;Y.prototype.releaseTile=function(a){if(a.getAttribute("tid")){a=a.getAttribute("tid");this.j[a]&&delete this.j[a];for(var b=0;b<this.H.length;b++){var c=this.H[b];c.j[a]&&delete c.j[a]}}};Y.prototype.releaseTile=Y.prototype.releaseTile;
Y.prototype.Q=function(a){this.e=a;var b=this.j;for(var c in b)if(b.hasOwnProperty(c))for(var d=b[c].childNodes,e=0;e<d.length;e++)y(d[e],a)};function Z(a,b){b=b||{};this.d=a instanceof S?a:new S(a);this.minZoom=b.minZoom;this.maxZoom=b.maxZoom;this.e=b.opacity||1;this.ga=b.ma||{};this.D=this.z=false;this.n=null;b.map&&this.setMap(b.map)}Z.prototype=new l.OverlayView;
Z.prototype.onAdd=function(){var a=document.createElement("div");a.style.position="absolute";a.style.border="none";this.n=a;this.getPanes().overlayLayer.appendChild(a);this.e&&y(a,this.e);var b=this;this.fa=l.event.addListener(this.getMap(),"bounds_changed",function(){$(b)})};Z.prototype.onAdd=Z.prototype.onAdd;Z.prototype.onRemove=function(){l.event.removeListener(this.fa);this.n.parentNode.removeChild(this.n);this.n=null};Z.prototype.onRemove=Z.prototype.onRemove;
Z.prototype.draw=function(){if(!this.z||this.D===true)$(this)};Z.prototype.draw=Z.prototype.draw;Z.prototype.Q=function(a){this.e=a=Math.min(Math.max(a,0),1);y(this.n,a)};
function $(a){if(a.z===true)a.D=true;else{var b=a.getMap(),c=b?b.getBounds():null;if(c){var d=a.ga;d.bounds=c;c=p;var e=b.getDiv();d.width=e.offsetWidth;d.height=e.offsetHeight;if((b=b.getProjection())&&b instanceof V)c=b.u;d.imageSR=c;x(a,"drawstart");a.z=true;a.n.style.backgroundImage="";U(a.d,d,function(f){a.z=false;if(a.D===true){a.D=false;$(a)}else{if(f.href){var j=a.getProjection(),h=f.bounds,g=j.fromLatLngToDivPixel(h.getSouthWest());j=j.fromLatLngToDivPixel(h.getNorthEast());h=a.n;h.style.left=
g.x+"px";h.style.top=j.y+"px";h.style.width=j.x-g.x+"px";h.style.height=g.y-j.y+"px";a.n.style.backgroundImage="url("+f.href+")";a.Q(a.e)}x(a,"drawend")}})}}};window.onload=function(){var a={zoom:13,center:new google.maps.LatLng(45.5,-122.7),mapTypeId:"arcgis",mapTypeControlOptions:{mapTypeIds:["arcgis",google.maps.MapTypeId.ROADMAP]},streetViewControl:true};a=new google.maps.Map(document.getElementById("map_canvas"),a);var b=new Y("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Portland/ESRI_LandBase_WebMercator/MapServer",{name:"ArcGIS"});a.mapTypes.set("arcgis",b);(new Z("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer")).setMap(a)};})()
