(function(){/*
 http://google-maps-utility-library-v3.googlecode.com
*/
var i,k=Math.PI/180,aa=0,m=google.maps,n,ca,o,p={ba:null,W:false},r={},t={};function u(a,b,c){var d=b===""?0:a.indexOf(b);return a.substring(d+b.length,c===""?a.length:a.indexOf(c,d+b.length))}function v(a){return a&&typeof a==="string"}function w(a,b,c){if(a&&b){var d;for(d in a)if(c||!(d in b))b[d]=a[d]}return b}function x(){m.event.trigger.apply(this,arguments)}
function da(a,b){var c="";if(a)c+=a.getTime()-a.getTimezoneOffset()*6E4;if(b)c+=", "+(b.getTime()-b.getTimezoneOffset()*6E4);return c}function y(a,b){b=Math.min(Math.max(b,0),1);if(a){var c=a.style;if(typeof c.opacity!=="undefined")c.opacity=b;if(typeof c.filters!=="undefined")c.filters.alpha.opacity=Math.floor(100*b);if(typeof c.filter!=="undefined")c.filter="alpha(opacity:"+Math.floor(b*100)+")"}}
function ea(a){var b="";for(var c in a)if(a.hasOwnProperty(c)){if(b.length>0)b+=";";b+=c+":"+a[c]}return b}function fa(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}throw new Error("This browser does not support XMLHttpRequest.");}else return new XMLHttpRequest}
var z="esriGeometryPoint",A="esriGeometryMultipoint",B="esriGeometryPolyline",C="esriGeometryPolygon",ga="esriGeometryEnvelope";
function ha(a){var b=a;if(a&&a.splice&&a.length>0)b=a[0];if(b instanceof m.LatLng||b instanceof m.Marker)return a&&a.splice&&a.length>1?A:z;else if(b instanceof m.Polyline)return B;else if(b instanceof m.Polygon)return C;else if(b instanceof m.LatLngBounds)return ga;else if(b.x!==undefined&&b.y!==undefined)return z;else if(b.points)return A;else if(b.paths)return B;else if(b.rings)return C;return null}
function ia(a){var b=a;if(a&&a.splice&&a.length>0)b=a[0];if(b&&b.splice&&b.length>0)b=b[0];if(b instanceof m.LatLng||b instanceof m.Marker||b instanceof m.Polyline||b instanceof m.Polygon||b instanceof m.LatLngBounds)return true;return false}function ja(a,b){for(var c=[],d,e=0,f=a.getLength();e<f;e++){d=a.getAt(e);c.push("["+d.lng()+","+d.lat()+"]")}b&&c.length>0&&c.push("["+a.getAt(0).lng()+","+a.getAt(0).lat()+"]");return c.join(",")}
function D(a){var b,c,d,e="{";switch(ha(a)){case z:b=a&&a.splice?a[0]:a;if(b instanceof m.Marker)b=b.getPosition();e+="x:"+b.lng()+",y:"+b.lat();break;case A:d=[];for(c=0;c<a.length;c++){b=a[c]instanceof m.Marker?a[c].getPosition():a[c];d.push("["+b.lng()+","+b.lat()+"]")}e+="points: ["+d.join(",")+"]";break;case B:d=[];a=a&&a.splice?a:[a];for(c=0;c<a.length;c++)d.push("["+ja(a[c].getPath())+"]");e+="paths:["+d.join(",")+"]";break;case C:d=[];b=a&&a.splice?a[0]:a;a=b.getPaths();for(c=0;c<a.getLength();c++)d.push("["+
ja(a.getAt(c),true)+"]");e+="rings:["+d.join(",")+"]";break;case ga:b=a&&a.splice?a[0]:a;e+="xmin:"+b.getSouthWest().lng()+",ymin:"+b.getSouthWest().lat()+",xmax:"+b.getNorthEast().lng()+",ymax:"+b.getNorthEast().lat();break}e+=", spatialReference:{wkid:4326}";e+="}";return e}function ka(a){var b=r[a.spatialReference.wkid||a.spatialReference.wkt];b=b||n;var c=b.q([a.xmin,a.ymin]);a=b.q([a.xmax,a.ymax]);return new m.LatLngBounds(new m.LatLng(c[1],c[0]),new m.LatLng(a[1],a[0]))}
function E(a){var b;if(typeof a==="object")if(a&&a.splice){b=[];for(var c=0,d=a.length;c<d;c++)b.push(E(a[c]));return"["+b.join(",")+"]"}else if(ia(a))return D(a);else if(a.toJSON)return a.toJSON();else{b="";for(c in a)if(a.hasOwnProperty(c)){if(b.length>0)b+=", ";b+=c+":"+E(a[c])}return"{"+b+"}"}return a.toString()}
function la(a){var b="";if(a){a.f=a.f||"json";for(var c in a)if(a.hasOwnProperty(c)&&a[c]!==null&&a[c]!==undefined){var d=E(a[c]);b+=c+"="+(escape?escape(d):encodeURIComponent(d))+"&"}}return b}
function F(a,b,c,d){var e="ags_jsonp_"+aa++ +"_"+Math.floor(Math.random()*1E6),f=null;b=b||{};b[c||"callback"]=e+" && "+e;b=la(b);var j=document.getElementsByTagName("head")[0];if(!j)throw new Error("document must have header tag");window[e]=function(){delete window[e];f&&j.removeChild(f);f=null;d.apply(null,arguments);x(t,"jsonpend",e)};if((b+a).length<2E3&&!p.W){f=document.createElement("script");f.src=a+(a.indexOf("?")===-1?"?":"&")+b;f.id=e;j.appendChild(f)}else{c=window.location;c=c.protocol+
"//"+c.hostname+(!c.port||c.port===80?"":":"+c.port+"/");var h=true;if(a.toLowerCase().indexOf(c.toLowerCase())!==-1)h=false;if(p.W)h=true;if(h&&!p.ba)throw new Error("No proxyUrl property in Config is defined");var g=fa();g.onreadystatechange=function(){if(g.readyState===4)if(g.status===200)eval(g.responseText);else throw new Error("Error code "+g.status);};g.open("POST",h?p.ba+"?"+a:a,true);g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");g.send(b)}x(t,"jsonpstart",e);return e}
t.sa=function(a,b,c,d){F(a,b,c,d)};t.V=function(a,b){if(b&&b.splice)for(var c,d=0,e=b.length;d<e;d++)if((c=b[d])&&c.splice)t.V(a,c);else ia(c)&&c.setMap(a)};t.wa=function(a,b){t.V(null,a);if(b)a.length=0};function G(a){a=a||{};this.wkid=a.wkid;this.wkt=a.wkt}G.prototype.forward=function(a){return a};G.prototype.q=function(a){return a};G.prototype.t=function(){return 360};G.prototype.toJSON=function(){return"{"+(this.wkid?" wkid:"+this.wkid:"wkt: '"+this.wkt+"'")+"}"};
function I(a){a=a||{};G.call(this,a)}I.prototype=new G;function J(a){a=a||{};G.call(this,a);var b=a.P,c=a.S*k,d=a.T*k,e=a.Q*k;this.a=a.u/a.unit;this.h=a.s*k;this.k=a.N;this.l=a.O;a=1/b;b=2*a-a*a;this.g=Math.sqrt(b);a=this.m(c,b);b=this.m(d,b);e=K(this,e,this.g);c=K(this,c,this.g);d=K(this,d,this.g);this.b=Math.log(a/b)/Math.log(c/d);this.L=a/(this.b*Math.pow(c,this.b));this.i=this.z(this.a,this.L,e,this.b)}J.prototype=new G;
J.prototype.m=function(a,b){var c=Math.sin(a);return Math.cos(a)/Math.sqrt(1-b*c*c)};function K(a,b,c){a=c*Math.sin(b);return Math.tan(Math.PI/4-b/2)/Math.pow((1-a)/(1+a),c/2)}i=J.prototype;i.z=function(a,b,c,d){return a*b*Math.pow(c,d)};i.w=function(a,b,c){c=b*Math.sin(c);return Math.PI/2-2*Math.atan(a*Math.pow((1-c)/(1+c),b/2))};i.R=function(a,b,c){var d=0;c=c;for(var e=this.w(a,b,c);Math.abs(e-c)>1.0E-9&&d<10;){d++;c=e;e=this.w(a,b,c)}return e};
i.forward=function(a){var b=a[0]*k;a=this.z(this.a,this.L,K(this,a[1]*k,this.g),this.b);b=this.b*(b-this.h);return[this.k+a*Math.sin(b),this.l+this.i-a*Math.cos(b)]};i.q=function(a){var b=a[0]-this.k,c=a[1]-this.l;a=Math.atan(b/(this.i-c));b=Math.pow((this.b>0?1:-1)*Math.sqrt(b*b+(this.i-c)*(this.i-c))/(this.a*this.L),1/this.b);return[(a/this.b+this.h)/k,this.R(b,this.g,Math.PI/2-2*Math.atan(b))/k]};i.t=function(){return Math.PI*2*this.a};
function L(a){a=a||{};G.call(this,a);this.a=a.u/a.unit;var b=a.P;this.D=a.oa;var c=a.Q*k;this.h=a.s*k;this.k=a.N;this.l=a.O;a=1/b;this.c=2*a-a*a;this.B=this.c*this.c;this.M=this.B*this.c;this.p=this.c/(1-this.c);this.U=this.m(c,this.a,this.c,this.B,this.M)}L.prototype=new G;L.prototype.m=function(a,b,c,d,e){return b*((1-c/4-3*d/64-5*e/256)*a-(3*c/8+3*d/32+45*e/1024)*Math.sin(2*a)+(15*d/256+45*e/1024)*Math.sin(4*a)-35*e/3072*Math.sin(6*a))};
L.prototype.forward=function(a){var b=a[1]*k,c=a[0]*k;a=this.a/Math.sqrt(1-this.c*Math.pow(Math.sin(b),2));var d=Math.pow(Math.tan(b),2),e=this.p*Math.pow(Math.cos(b),2);c=(c-this.h)*Math.cos(b);var f=this.m(b,this.a,this.c,this.B,this.M);return[this.k+this.D*a*(c+(1-d+e)*Math.pow(c,3)/6+(5-18*d+d*d+72*e-58*this.p)*Math.pow(c,5)/120),this.l+this.D*(f-this.U)+a*Math.tan(b)*(c*c/2+(5-d+9*e+4*e*e)*Math.pow(c,4)/120+(61-58*d+d*d+600*e-330*this.p)*Math.pow(c,6)/720)]};
L.prototype.q=function(a){var b=a[0],c=a[1];a=(1-Math.sqrt(1-this.c))/(1+Math.sqrt(1-this.c));c=(this.U+(c-this.l)/this.D)/(this.a*(1-this.c/4-3*this.B/64-5*this.M/256));a=c+(3*a/2-27*Math.pow(a,3)/32)*Math.sin(2*c)+(21*a*a/16-55*Math.pow(a,4)/32)*Math.sin(4*c)+151*Math.pow(a,3)/6*Math.sin(6*c)+1097*Math.pow(a,4)/512*Math.sin(8*c);c=this.p*Math.pow(Math.cos(a),2);var d=Math.pow(Math.tan(a),2),e=this.a/Math.sqrt(1-this.c*Math.pow(Math.sin(a),2)),f=this.a*(1-this.c)/Math.pow(1-this.c*Math.pow(Math.sin(a),
2),1.5);b=(b-this.k)/(e*this.D);e=a-e*Math.tan(a)/f*(b*b/2-(5+3*d+10*c-4*c*c-9*this.p)*Math.pow(b,4)/24+(61+90*d+28*c+45*d*d-252*this.p-3*c*c)*Math.pow(b,6)/720);return[(this.h+(b-(1+2*d+c)*Math.pow(b,3)/6+(5-2*c+28*d-3*c*c+8*this.p+24*d*d)*Math.pow(b,5)/120)/Math.cos(a))/k,e/k]};L.prototype.t=function(){return Math.PI*2*this.a};function M(a){a=a||{};G.call(this,a);this.a=(a.u||6378137)/(a.unit||1);this.h=(a.s||0)*k}M.prototype=new G;
M.prototype.forward=function(a){var b=a[1]*k;return[this.a*(a[0]*k-this.h),this.a/2*Math.log((1+Math.sin(b))/(1-Math.sin(b)))]};M.prototype.q=function(a){return[(a[0]/this.a+this.h)/k,(Math.PI/2-2*Math.atan(Math.exp(-a[1]/this.a)))/k]};M.prototype.t=function(){return Math.PI*2*this.a};
function N(a){a=a||{};G.call(this,a);var b=a.P,c=a.S*k,d=a.T*k,e=a.Q*k;this.a=a.u/a.unit;this.h=a.s*k;this.k=a.N;this.l=a.O;a=1/b;b=2*a-a*a;this.g=Math.sqrt(b);a=this.m(c,b);b=this.m(d,b);c=R(this,c,this.g);d=R(this,d,this.g);e=R(this,e,this.g);this.b=(a*a-b*b)/(d-c);this.K=a*a+this.b*c;this.i=this.z(this.a,this.K,this.b,e)}N.prototype=new G;N.prototype.m=function(a,b){var c=Math.sin(a);return Math.cos(a)/Math.sqrt(1-b*c*c)};
function R(a,b,c){a=c*Math.sin(b);return(1-c*c)*(Math.sin(b)/(1-a*a)-1/(2*c)*Math.log((1-a)/(1+a)))}i=N.prototype;i.z=function(a,b,c,d){return a*Math.sqrt(b-c*d)/c};i.w=function(a,b,c){var d=b*Math.sin(c);return c+(1-d*d)*(1-d*d)/(2*Math.cos(c))*(a/(1-b*b)-Math.sin(c)/(1-d*d)+Math.log((1-d)/(1+d))/(2*b))};i.R=function(a,b,c){var d=0;c=c;for(var e=this.w(a,b,c);Math.abs(e-c)>1.0E-8&&d<10;){d++;c=e;e=this.w(a,b,c)}return e};
i.forward=function(a){var b=a[0]*k;a=this.z(this.a,this.K,this.b,R(this,a[1]*k,this.g));b=this.b*(b-this.h);return[this.k+a*Math.sin(b),this.l+this.i-a*Math.cos(b)]};i.q=function(a){var b=a[0]-this.k;a=a[1]-this.l;var c=Math.sqrt(b*b+(this.i-a)*(this.i-a)),d=this.b>0?1:-1;c=(this.K-c*c*this.b*this.b/(this.a*this.a))/this.b;return[(Math.atan(d*b/(d*this.i-d*a))/this.b+this.h)/k,this.R(c,this.g,Math.asin(c/2))/k]};i.t=function(){return Math.PI*2*this.a};i.t=function(){return Math.PI*2*this.a};n=new I({wkid:4326});
ca=new I({wkid:4269});o=new M({wkid:102113,u:6378137,s:0,unit:1});r={"4326":n,"4269":ca,"102113":o,"102100":new M({wkid:102100,u:6378137,s:0,unit:1})};
t.va=function(a,b){var c=r[""+a];if(c)return c;if(b instanceof G)c=r[""+a]=b;else{c=b||a;var d={wkt:a};if(a===parseInt(a,10))d={wkid:a};var e=u(c,'PROJECTION["','"]'),f=u(c,"SPHEROID[","]").split(",");if(e!==""){d.unit=parseFloat(u(u(c,"PROJECTION",""),"UNIT[","]").split(",")[1]);d.u=parseFloat(f[1]);d.P=parseFloat(f[2]);d.Q=parseFloat(u(c,'"Latitude_Of_Origin",',"]"));d.s=parseFloat(u(c,'"Central_Meridian",',"]"));d.N=parseFloat(u(c,'"False_Easting",',"]"));d.O=parseFloat(u(c,'"False_Northing",',
"]"))}switch(e){case "":c=new G(d);break;case "Lambert_Conformal_Conic":d.S=parseFloat(u(c,'"Standard_Parallel_1",',"]"));d.T=parseFloat(u(c,'"Standard_Parallel_2",',"]"));c=new J(d);break;case "Transverse_Mercator":d.oa=parseFloat(u(c,'"Scale_Factor",',"]"));c=new L(d);break;case "Albers":d.S=parseFloat(u(c,'"Standard_Parallel_1",',"]"));d.T=parseFloat(u(c,'"Standard_Parallel_2",',"]"));c=new N(d);break;default:throw new Error(e+"  not supported");}if(c)r[""+a]=c}return c};
function ma(a){this.url=a;this.definition=null}ma.prototype.load=function(){var a=this;this.r||F(this.url,{},"",function(b){w(b,a);a.r=true;x(a,"load")})};function S(a,b){this.url=a;this.r=false;var c=a.split("/");this.name=c[c.length-2].replace(/_/g," ");b=b||{};b.pa||qa(this)}function qa(a){F(a.url,{},"",function(b){a.C(b)})}
S.prototype.C=function(a){var b=this;w(a,this);this.spatialReference=a.spatialReference.wkt?G.ua(a.spatialReference.wkt):r[a.spatialReference.wkid];a.tables!==undefined?F(this.url+"/layers",{},"",function(c){ra(b,c)}):ra(b,a)};
function ra(a,b){var c=[],d=[];a.layers=c;if(b.tables)a.tables=d;var e,f,j,h;f=0;for(j=b.layers.length;f<j;f++){h=b.layers[f];e=new ma(a.url+"/"+h.id);w(h,e);e.visible=e.defaultVisibility;c.push(e)}if(b.tables){f=0;for(j=b.tables.length;f<j;f++){h=b.tables[f];e=new ma(a.url+"/"+h.id);w(h,e);d.push(e)}}f=0;for(j=c.length;f<j;f++){e=c[f];if(e.subLayerIds){e.I=[];d=0;for(h=e.subLayerIds.length;d<h;d++){var g;a:{g=e.subLayerIds[d];var l=a.layers;if(l)for(var s=0,q=l.length;s<q;s++){if(g===l[s].id){g=
l[s];break a}if(v(g)&&l[s].name.toLowerCase()===g.toLowerCase()){g=l[s];break a}}g=null}e.I.push(g);g.na=e}}}a.r=true;x(a,"load")}function sa(a){var b={};if(a.layers)for(var c=0,d=a.layers.length;c<d;c++){var e=a.layers[c];if(e.definition)b[String(e.id)]=e.definition}return b}
function ta(a){var b=[];if(a.layers){var c,d,e;d=0;for(e=a.layers.length;d<e;d++){c=a.layers[d];if(c.I)for(var f=0,j=c.I.length;f<j;f++)if(c.I[f].visible===false){c.visible=false;break}}d=0;for(e=a.layers.length;d<e;d++){c=a.layers[d];c.visible===true&&b.push(c.id)}}return b}
function ua(a,b,c,d){if(b&&b.bounds){var e={};e.f=b.f;var f=b.bounds;e.bbox=""+f.getSouthWest().lng()+","+f.getSouthWest().lat()+","+f.getNorthEast().lng()+","+f.getNorthEast().lat();e.size=""+b.width+","+b.height;e.dpi=b.dpi;if(b.imageSR)e.imageSR=b.imageSR.wkid?b.imageSR.wkid:"{wkt:"+b.imageSR.wkt+"}";e.bboxSR="4326";e.format=b.format;f=b.layerDefinitions;if(f===undefined)f=sa(a);e.layerDefs=ea(f);f=b.layerIds;var j=b.layerOption||"show";if(f===undefined)f=ta(a);if(f.length>0)e.layers=j+":"+f.join(",");
else if(a.r&&c){c({href:null});return}e.transparent=b.transparent===false?false:true;if(b.time)e.time=da(b.time,b.qa);e.ia=b.ia;if(e.f==="image")return a.url+"/export?"+la(e);else F(a.url+"/export",e,"",function(h){if(h.extent){h.bounds=ka(h.extent);delete h.extent;c(h)}else{h=h.error;d&&h&&h.error&&d(h.error)}})}}
function va(a,b,c,d){if(b){var e={};e.geometry=D(b.geometry);e.geometryType=ha(b.geometry);e.mapExtent=D(b.bounds);e.tolerance=b.tolerance||2;e.sr=4326;e.imageDisplay=""+b.width+","+b.height+","+(b.dpi||96);e.layers=b.layerOption||"all";if(b.layerIds)e.layers+=":"+b.layerIds.join(",");if(b.layerDefs)e.layerDefs=ea(b.layerDefs);e.ka=b.ka;e.returnGeometry=b.returnGeometry===false?false:true;F(a.url+"/identify",e,"",function(f){var j,h,g;if(f.results)for(j=0;j<f.results.length;j++){h=f.results[j];a:{g=
h.geometry;var l=b.overlayOptions,s=null,q=void 0,O=void 0,na=void 0;q=void 0;var oa=void 0,P=void 0,H=void 0,ba=void 0,Q=void 0;l=l||{};if(g){s=[];if(g.x){q=new m.Marker(w(l.markerOptions||l,{position:new m.LatLng(g.y,g.x)}));s.push(q)}else{P=g.points||g.paths||g.rings;if(!P){g=s;break a}var pa=[];O=0;for(na=P.length;O<na;O++){H=P[O];if(g.points){q=new m.Marker(w(l.markerOptions||l,{position:new m.LatLng(H[1],H[0])}));s.push(q)}else{Q=[];q=0;for(oa=H.length;q<oa;q++){ba=H[q];Q.push(new m.LatLng(ba[1],
ba[0]))}if(g.paths){q=new m.Polyline(w(l.polylineOptions||l,{path:Q}));s.push(q)}else g.rings&&pa.push(Q)}}if(g.rings){q=new m.Polygon(w(l.ta||l,{paths:pa}));s.push(q)}}}g=s}h.ha={geometry:g,attributes:h.attributes};delete h.attributes}c(f);d&&f&&f.error&&d(f.error)})}}
function T(a){this.ja=a?a.lods:null;this.v=a?r[a.spatialReference.wkid||a.spatialReference.wkt]:o;if(!this.v)throw new Error("unsupported Spatial Reference");this.ca=a?a.lods[0].resolution:156543.033928;this.minZoom=Math.floor(Math.log(this.v.t()/this.ca/256)/Math.LN2+0.5);this.maxZoom=a?this.minZoom+this.ja.length-1:20;if(m.Size)this.da=a?new m.Size(a.cols,a.rows):new m.Size(256,256);this.G=Math.pow(2,this.minZoom)*this.ca;this.$=a?a.origin.x:-2.0037508342787E7;this.aa=a?a.origin.y:2.0037508342787E7;
if(a)for(var b,c=0;c<a.lods.length-1;c++){b=a.lods[c].resolution/a.lods[c+1].resolution;if(b>2.001||b<1.999)throw new Error("This type of map cache is not supported in V3. \nScale ratio between zoom levels must be 2");}}T.prototype.fromLatLngToPoint=function(a,b){if(!a||isNaN(a.lat())||isNaN(a.lng()))return null;var c=this.v.forward([a.lng(),a.lat()]),d=b||new m.Point(0,0);d.x=(c[0]-this.$)/this.G;d.y=(this.aa-c[1])/this.G;return d};T.prototype.fromLatLngToPoint=T.prototype.fromLatLngToPoint;
T.prototype.fromPointToLatLng=function(a){if(a===null)return null;a=this.v.q([a.x*this.G+this.$,this.aa-a.y*this.G]);return new m.LatLng(a[1],a[0])};var wa=new T;
function U(a,b){b=b||{};if(b.opacity){this.e=b.opacity;delete b.opacity}w(b,this);this.d=a instanceof S?a:new S(a);if(b.X){var c=u(this.d.url,"","://");this.ea=c+"://"+b.X+u(this.d.url,c+"://"+u(this.d.url,"://","/"),"");this.Z=parseInt(u(b.X,"[","]"),10)}this.name=b.name||this.d.name;this.maxZoom=b.maxZoom||19;this.minZoom=b.minZoom||0;if(this.d.r)this.C(b);else{var d=this;m.event.addListenerOnce(this.d,"load",function(){d.C(b)})}this.j={};this.Y=b.map}
U.prototype.C=function(a){if(this.d.tileInfo){this.o=new T(this.d.tileInfo);this.minZoom=a.minZoom||this.o.minZoom;this.maxZoom=a.maxZoom||this.o.maxZoom}};
U.prototype.getTileUrl=function(a,b){var c=b-(this.o?this.o.minZoom:this.minZoom),d="";if(!isNaN(a.x)&&!isNaN(a.y)&&c>=0&&a.x>=0&&a.y>=0){d=this.d.url;if(this.ea)d=this.ea.replace("["+this.Z+"]",""+(a.y+a.x)%this.Z);if(this.d.singleFusedMapCache===false){c=this.o||this.Y?this.Y.getProjection():wa;if(!c instanceof T)c=wa;d=c.da;var e=1<<b,f=new m.Point(a.x*d.width/e,(a.y+1)*d.height/e);e=new m.Point((a.x+1)*d.width/e,a.y*d.height/e);f=new m.LatLngBounds(c.fromPointToLatLng(f),c.fromPointToLatLng(e));
e={f:"image"};e.bounds=f;e.width=d.width;e.height=d.height;e.imageSR=c.v;d=ua(this.d,e)}else d=d+"/tile/"+c+"/"+a.y+"/"+a.x}return d};U.prototype.H=function(a){this.e=a;var b=this.j;for(var c in b)b.hasOwnProperty(c)&&y(b[c],a)};
function V(a,b){b=b||{};var c;if(b.opacity){this.e=b.opacity;delete b.opacity}w(b,this);var d=a;if(v(a))d=[new U(a,b)];else if(a instanceof S)d=[new U(a,b)];else if(a instanceof U)d=[a];else if(a.length>0&&v(a[0])){d=[];for(c=0;c<a.length;c++)d[c]=new U(a[c],b)}this.J=d;this.j={};if(b.maxZoom!==undefined)this.maxZoom=b.maxZoom;else{var e=0;for(c=0;c<d.length;c++)e=Math.max(e,d[c].maxZoom);this.maxZoom=e}if(d[0].o){this.tileSize=d[0].o.da;this.projection=d[0].o}else this.tileSize=new m.Size(256,256);
if(!this.name)this.name=d[0].name}
V.prototype.getTile=function(a,b,c){for(var d=c.createElement("div"),e="_"+a.x+"_"+a.y+"_"+b,f=0;f<this.J.length;f++){var j=this.J[f];if(b<=j.maxZoom&&b>=j.minZoom){var h=j.getTileUrl(a,b);if(h){var g=c.createElement(document.all?"img":"div");g.style.border="0px none";g.style.margin="0px";g.style.padding="0px";g.style.overflow="hidden";g.style.position="absolute";g.style.top="0px";g.style.left="0px";g.style.width=""+this.tileSize.width+"px";g.style.height=""+this.tileSize.height+"px";if(document.all)g.src=
h;else g.style.backgroundImage="url("+h+")";d.appendChild(g);j.j[e]=g;if(j.e!==undefined)y(g,j.e);else this.e!==undefined&&y(g,this.e)}}}this.j[e]=d;d.setAttribute("tid",e);return d};V.prototype.getTile=V.prototype.getTile;V.prototype.releaseTile=function(a){if(a.getAttribute("tid")){a=a.getAttribute("tid");this.j[a]&&delete this.j[a];for(var b=0;b<this.J.length;b++){var c=this.J[b];c.j[a]&&delete c.j[a]}}};V.prototype.releaseTile=V.prototype.releaseTile;
V.prototype.H=function(a){this.e=a;var b=this.j;for(var c in b)if(b.hasOwnProperty(c))for(var d=b[c].childNodes,e=0;e<d.length;e++)y(d[e],a)};function W(a,b){b=b||{};this.d=a instanceof S?a:new S(a);this.minZoom=b.minZoom;this.maxZoom=b.maxZoom;this.e=b.opacity||1;this.ga=b.ra||{};this.F=this.A=false;this.n=null;b.map&&this.setMap(b.map)}W.prototype=new m.OverlayView;
W.prototype.onAdd=function(){var a=document.createElement("div");a.style.position="absolute";a.style.border="none";this.n=a;this.getPanes().overlayLayer.appendChild(a);this.e&&y(a,this.e);var b=this;this.fa=m.event.addListener(this.getMap(),"bounds_changed",function(){X(b)})};W.prototype.onAdd=W.prototype.onAdd;W.prototype.onRemove=function(){m.event.removeListener(this.fa);this.n.parentNode.removeChild(this.n);this.n=null};W.prototype.onRemove=W.prototype.onRemove;
W.prototype.draw=function(){if(!this.A||this.F===true)X(this)};W.prototype.draw=W.prototype.draw;W.prototype.H=function(a){this.e=a=Math.min(Math.max(a,0),1);y(this.n,a)};
function X(a){if(a.A===true)a.F=true;else{var b=a.getMap(),c=b?b.getBounds():null;if(c){var d=a.ga;d.bounds=c;c=o;var e=b.getDiv();d.width=e.offsetWidth;d.height=e.offsetHeight;if((b=b.getProjection())&&b instanceof T)c=b.v;d.imageSR=c;x(a,"drawstart");a.A=true;a.n.style.backgroundImage="";ua(a.d,d,function(f){a.A=false;if(a.F===true){a.F=false;X(a)}else{if(f.href){var j=a.getProjection(),h=f.bounds,g=j.fromLatLngToDivPixel(h.getSouthWest());j=j.fromLatLngToDivPixel(h.getNorthEast());h=a.n;h.style.left=
g.x+"px";h.style.top=j.y+"px";h.style.width=j.x-g.x+"px";h.style.height=g.y-j.y+"px";a.n.style.backgroundImage="url("+f.href+")";a.H(a.e)}x(a,"drawend")}})}}}var xa=S,ya=t,za=W,Aa=V;var Y,Z,$,Ba;
function Ca(){var a=document.getElementById("svc");a="http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/"+a.options[a.selectedIndex].text;if(Z!=null){if(Z instanceof za)Z.setMap(null);else Z instanceof Aa&&Y.overlayMapTypes.removeAt(0);Z=null}$=new xa(a);google.maps.event.addListener($,"load",function(){var b;b=$.initialExtent?ka($.initialExtent):null;if(b)if(b.getSouthWest().lng()>b.getNorthEast().lng()){Y.setCenter(new google.maps.LatLng(40,-100));Y.setZoom(4)}else b.contains(Y.getCenter())||Y.fitBounds(b);
b=document.getElementById("op").value;if($.singleFusedMapCache){Z=new Aa($,{opacity:b});Y.overlayMapTypes.insertAt(0,Z)}else{Z=new za($,{opacity:b});Z.setMap(Y)}b="This is a <b>dynamic</b> map svc. You can turn on/off individual layers using the check box.";if($.singleFusedMapCache)b="This is a <b>cached</b> map svc. You can <b>NOT</b> turn on/off individual layers.";document.getElementById("svcInfo").innerHTML=b;document.getElementById("svcDesc").innerHTML=$.description+"<br/>Copyright:"+$.copyrightText;
b=' <select id="clickOpts" style="font-size:9pt;width:200px" onchange="onClickOptionChanged()">';b+='<option value="top">&lt;Top-most layer&gt;</option>';b+='<option value="visible">&lt;Visible layers&gt;</option>';b+='<option value="all">&lt;All layers&gt;</option>';for(var c=$.layers,d=0;d<c.length;d++){var e=c[d];google.maps.event.addListenerOnce(e,"load",Da);e.load();e.subLayerIds||(b+='<option value="all:'+d+'">'+e.name+"</option>")}document.getElementById("clickOptsDiv").innerHTML=b+"</select>"})}
function Da(){if(Z&&$.r){for(var a="",b=5.91657527591555E8/Math.pow(2,Y.getZoom()),c=$.layers,d=0;d<c.length;d++){var e=c[d],f;f=e.la&&e.la>b?false:e.ma&&e.ma<b?false:true;a+='<div style="color:'+(f?"black":"gray")+'">';if(e.subLayerIds)a+=e.name+"(group)<br/>";else{if(e.na)a+="&nbsp;&nbsp;&nbsp;&nbsp;";a+='<input type="checkbox" id="layer'+e.id+'"';if(e.visible)a+=' checked="checked"';if(!f||$.singleFusedMapCache)a+=' disabled="disabled"';a+=' onclick="setLayerVisibility()">'+e.name+"<br/>"}a+="</div>"}document.getElementById("toc").innerHTML=
a}}
function Ea(a){if(a){var b=document.getElementById("clickOpts").value;if(Z&&$.r)va($,{geometry:a,layerOption:b||"top",tolerance:5,bounds:Y.getBounds(),width:Y.getDiv().offsetWidth,height:Y.getDiv().offsetHeight,returnGeometry:false},function(c,d){if(d)alert(d.message+"\n"+d.details.join("\n"));else if(c.results){var e="";if(c.results){e+="Total # of Results:"+c.results.length;for(var f=0,j=c.results.length;f<j;f++){var h=c.results[f];if(f>0)e+="<hr/>";e+="<div>Result #"+(f+1)+": <i>"+h.value+"</i><br/><table>";e+=
"<tr><td>From layer: <b>"+h.layerName+"</b></td></tr>";e+='<tr><td > <table style="font-size:9pt">';h=h.ha.attributes;for(var g in h)if(h.hasOwnProperty(g)){e+="<tr>";e+='<td style="background-color:#DDDDDD;">'+g+"</td>";var l=h[g];e+="<td>"+(l===null||typeof l==="undefined"?"":""+l)+"</td></tr>"}e+="</table></td></tr></table></div>"}document.getElementById("info").innerHTML=e;if(Ba==null)Ba=new google.maps.Marker({position:a,map:Y});else Ba.setPosition(a)}}})}}
window.onload=function(){var a={zoom:4,center:new google.maps.LatLng(40,-100),mapTypeId:google.maps.MapTypeId.ROADMAP,draggableCursor:"default"};Y=new google.maps.Map(document.getElementById("map_canvas"),a);Ca();google.maps.event.addListener(Y,"click",function(b){Ea(b.latLng)});google.maps.event.addListener(Y,"zoom_changed",Da);google.maps.event.addListener(ya,"jsonpstart",function(){document.getElementById("working").style.visibility="visible"});google.maps.event.addListener(ya,"jsonpend",function(){document.getElementById("working").style.visibility=
"hidden"})};window.setLayerVisibility=function(){for(var a=$.layers,b=0;b<a.length;b++){var c=document.getElementById("layer"+a[b].id);if(c)a[b].visible=c.checked===true}X(Z)};window.loadMapService=Ca;window.setOVOpacity=function(a){Z&&Z.H(a)};})()
